name: Build and Testing Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
      
jobs:
  cache-and-install:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ensure pnpm store directory exists
        run: mkdir -p ~/.pnpm-store

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

  testing:
    runs-on: ubuntu-22.04
    needs: cache-and-install  # Depends on cache-and-install

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ensure pnpm store directory exists
        run: mkdir -p ~/.pnpm-store

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Restore pnpm cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Run Testing Checks
        run: pnpm test

  build:
    runs-on: ubuntu-22.04
    needs: cache-and-install  # Depends on cache-and-install

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Ensure pnpm store directory exists
        run: mkdir -p ~/.pnpm-store

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Restore pnpm cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build
